### ISSUE TITLE
application.properties code style

### ISSUE THREAD

**Issue by evershauke** [spring-guides/gs-uploading-files#17]
Hi, 

I just read the guide for uploading files (https://spring.io/guides/gs/uploading-files/) and in the passage with the application.properties settings:

multipart.maxFileSize: 128KB
multipart.maxRequestSize: 128KB

which is the slightly "inconsistent" code style for key/value pairs in properties-files. It would be more consistent if one would rename it to:

multipart.maxFileSize= 128KB
multipart.maxRequestSize= 128KB

**Comment by dsyer** [comment]
What's inconsistent about it? Those are the only 2 properties.

**Comment by evershauke** [comment]
Because they use a different code style in their other documents/references and IDEA will give out a warning. (see: http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)

**Comment by dsyer** [comment]
I consider that a bug in IDEA then. I'm not sure it needs to lead to a change here (this guide is internally consistent and correct).

**Comment by evershauke** [comment]
I agree that it's a minor issue. You may close this then.
