### ISSUE TITLE
Documentation Errata

### ISSUE THREAD

**Issue by davidbuhler** [spring-guides/gs-uploading-files#20]
Hello,

I believe the example given in the documentation has a small issue with the given syntax. The colon should be an equals sign.

URL: https://spring.io/guides/gs/uploading-files/
Section: Tuning file upload limits

Actual Example
`multipart.maxFileSize: 128KB
multipart.maxRequestSize: 128KB`

Expected Example
`multipart.maxFileSize=128KB
multipart.maxRequestSize=128KB`

**Comment by dsyer** [comment]
I'm guessing you didn't try it then because colons are valid separators in properties files (see JDK docs).

**Comment by davidbuhler** [comment]
Noted. I got an error in IntelliJ, and assumed incorrectly.

**Comment by gregturn** [comment]
If you posted a screenshot of IntelliJ's error, we could forward that to Jetbrains to avoid in the future.
