### ISSUE TITLE
Stream Close

### ISSUE THREAD

**Issue by ahmedbaberkhan** [spring-guides/gs-uploading-files#22]
stream.close in handleFileUpload function of FileUploadController is not required. FileCopyUtils.copy close both input and output stream.

**Comment by gregturn** [comment]
@ahmedbaberkhan Have you signed our Spring CLA?

**Comment by ahmedbaberkhan** [comment]
No, I did not sign.

**Comment by gregturn** [comment]
If you fill out the details here => https://support.springsource.com/spring_committer_signup, should line things up so we can accept your contribution.

**Comment by ahmedbaberkhan** [comment]
Could you please tell me what to enter as Project Lead?

**Comment by gregturn** [comment]
Spring Data Access => Oliver Gierke

(It's not critical what you pick, but that you "sign")

**Comment by ahmedbaberkhan** [comment]
Done!

**Comment by gregturn** [comment]
I appreciate your effort @ahmedbaberkhan, but I needed to essentially rewrite the code using Java NIO + Java 8 streams, while also serving up hyperlinks to all the files. Hence, that change removed the need for this patch.
