### ISSUE TITLE
No `@Service` annotation on `StorageService`

### ISSUE THREAD

**Issue by Ruben9922** [spring-guides/gs-uploading-files#31]
There is no `@Service` annotation on the `StorageService`, resulting in a `NoSuchBeanDefinitionException`.  
However, I seem to be using an older version of Spring than the one used in the tutorial (using v4.2.7, which doesn't support `@GetMapping` and `@PostMapping` annotations, which are used in the tutorial). I'm also quite new to Spring.

**Comment by dsyer** [comment]
`StorageService` is an interface. The concrete implementation `FileSystemStorageService` is annotated with `@Service`. So whatever problem you have, it's not what you said. If you need help, make sure you can compile and run the "complete" sample, and then compare it with what you did.

**Comment by Ruben9922** [comment]
Ah yeah, didn't see that. The "complete" project compiled and ran fine. Compared the relevant files and seems like the only thing I did differently was use a different package name, but currently still unsure as to why that would be a problem - I'll look into that further.  
Thanks for your help.

**Comment by bclozel** [comment]
@Ruben9922 Your components are probably not scanned then - make sure that all your app components are located under the package where your Application class lives. Check out `@SpringApplication` [in the reference doc](http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-using-springbootapplication-annotation.html).

**Comment by Ruben9922** [comment]
@bclozel Got it running in the end :smile:
All the components were inside the same package, but after looking more closely at the documentation I found I missed out one of the annotations added by `@SpringApplication` (`@Configuration` I think - don't have the code in front of me at the moment) and hadn't added `StorageProperties.class` to `@EnableConfigurationProperties`.  
Now I'm getting an unrelated security-related error (HTTP 500 error to do with CSRF tokens or something, but can't remember exactly) when uploading a file, but I'll look at the documentation and try to sort that out later.

**Comment by Ruben9922** [comment]
For the record, I fixed the CSRF token issue [using this StackOverflow answer](http://stackoverflow.com/a/29917946). I just included the CSRF token in the form's action using Thymeleaf:

    <form method="POST" enctype="multipart/form-data" action="/" th:action="|/?${_csrf.parameterName}=${_csrf.token}|">

Now the application works fully.
