### ISSUE TITLE
Incorporate /storage into tutorial

### ISSUE THREAD

**Issue by ptMcGit** [spring-guides/gs-uploading-files#33]
In README.adoc the section "Make the application executable" can't be completed without /storage in place i.e. there needs to be a section for adding the files in src/main/java/hello/storage.

Sorry about the confusion.

**Comment by dsyer** [comment]
What is "/storage"? What do you have to do to put it "in place"? (I don't have to do anything special. Just run the app from the command line.)

**Comment by Avec112** [comment]
I think ptMcGit maybe is refering to the documentation https://spring.io/guides/gs/uploading-files/ and the fact that you have to get the storage files from repo while the controller for instance is available from the article.

**Comment by dsyer** [comment]
I see. There is a `StorageService` in the sample app that isn't mentioned anywhere in the text.

**Comment by AndreiD** [comment]
up this issue. C'mon man!!!
