### ISSUE TITLE
Anyway to port this to Java 1.7 code ?

### ISSUE THREAD

**Issue by bulltorious** [spring-guides/gs-uploading-files#35]
I don't know if this is the correct spot to post something like this, but is there anyway you could fork this and demonstrate it using Java 1.7 code?  I would like to use spring boot because of its elegance, but am unfortunately stuck to using 1.7.

**Comment by gregturn** [comment]
We've already spent the effort upgrading to Java 8 driven by its huge uptake and Java 7 being EOL. 

If you load the code into your Java 7 IDE and mention the bits that are confusing sounds like a good candidate for stackofwrflow. But forking to go back to an older version of Java is not something we can spend time on.

**Comment by bulltorious** [comment]
OK, yes I sent it to stackoverflow and got some answers...thanks for your consideration.  Spring Boot makes java web development much easier !

**Comment by gregturn** [comment]
Great!
