### ISSUE TITLE
FILES DELETED ON MAC OS 10.13.2!!!!!

### ISSUE THREAD

**Issue by chenjiangtao** [spring-guides/gs-uploading-files#39]
When I run this program ,I updated the location to my home folder,like this 
`private String location = "/Users/home/jiangtao"` ,
then I open the url `http://localhost:8080/` , see a lot of files and folders..... I click some one type is folder to download......the horrible things coming,all my files and folders in the director `/Users/home/jiangtao`  start deleting .......

the chrome download path is `/Users/home/jiangtao/Downloads`

evn:

> 
> Mac OS 10.13.2
> Java 8
> IntelliJ IDEA, Chrome

 

- update the location
![](http://static.tuzhihao.com//41514119626_.pic.jpg?imageMogr2/thumbnail/!100p)
- the load method
![](http://static.tuzhihao.com//21514119626_.pic.jpg?imageMogr2/thumbnail/!100p)
- my mac system file deleted
![](http://static.tuzhihao.com//1514120967.png?imageMogr2/thumbnail/!100p)
- just few seconds my computer deleted more than 100G
![](http://static.tuzhihao.com//31514119626_.pic_hd.jpg?imageMogr2/thumbnail/!100p)

**Comment by bennypi** [comment]
Well that sounds very unfortunate, but I guess this is exactly how the application is supposed to work.

Take a look at https://github.com/spring-guides/gs-uploading-files/blob/d9865cb0a0420390609551cfb089d766d4e13188/complete/src/main/java/hello/Application.java#L23
This line says that on startup of the application the content of the upload-dir is deleted recursively. And this is exactly was happened in your case.

Maybe there should be a warning somwhere that the upload-dir is deleted on startup.

**Comment by chenjiangtao** [comment]
Oooh, my god ,you're right.....Thank you very much @bennypi  
run the example must be careful....Jesus...
