### ISSUE TITLE
Max file/request size config item

### ISSUE THREAD

**Issue by mpesa1975** [spring-guides/gs-uploading-files#42]
Hi,
I found one discrepancy at https://spring.io/guides/gs/uploading-files/:

spring.**servlet**.multipart.max-file-size=128KB
spring.**servlet**.multipart.max-request-size=128KB

versus

spring.**http**.multipart.max-file-size
spring.**http**.multipart.max-request-size

Which one is correct?

**Comment by gregturn** [comment]
`spring.http.multpart.*` has been deprecated.

**Comment by mpesa1975** [comment]
Since which version?

**Comment by gregturn** [comment]
This probably occurred in Boot 2.0. They went through and normalized a lot of properties.
