### ISSUE TITLE
Parameter 0 of constructor in com.example.uploadingfiles.FileUploadController required a bean of type 'com.example.uploadingfiles.storage.StorageService' that could not be found.

### ISSUE THREAD

**Issue by pramodya1994** [spring-guides/gs-uploading-files#67]
I get the above error when I'm trying to build the project.

**Comment by ahowe442** [comment]
I get the same message with the demo project.  `Parameter 0 of constructor in com.example.springdemouploadingfiles.FileUploadController required a bean of type 'com.example.springdemouploadingfiles.storage.StorageService' that could not be found.
`

**Comment by sandeepan-nath** [comment]
@pramodya1994  @ahowe442  I was also getting this when I was following the spring guide. I added FileSystemStorageService as in gs-uploading-files/complete and it got resolved.

**Comment by ahowe442** [comment]
@sandeepan-nath thank you!  I wish that fixed it for me, but it did not.  Are you using maven? or Gradle?  I'm using gradle.

**Comment by sandeepan-nath** [comment]
@ahowe442  I must have used maven.

**Comment by willynganga** [comment]
I got that error too. This is how I solved it: Place the @Autowired annotation on top of the StorageService field.

**Comment by ahmadshalabi** [comment]
You need to add the **@Component** on top of the StorageSerivce class so the SpringBoot can detect it.

**Comment by utibeng** [comment]
> You need to add the **@component** on top of the StorageSerivce class so the SpringBoot can detect it.

this doesn't work for me

**Comment by Abebayehu-Alaro** [comment]
> I get the same message with the demo project. `Parameter 0 of constructor in com.example.springdemouploadingfiles.FileUploadController required a bean of type 'com.example.springdemouploadingfiles.storage.StorageService' that could not be found. `

add the FileSystemStorageService.java file (complete/src/main/java/com/example/uploadingfiles/storage/FileSystemStorageService.java) in the same package and build it.

**Comment by Buzzardo** [comment]
I assigned this to myself, because it looks like we missed telling people to add FileSystemStorageService in the readme.

**Comment by Buzzardo** [comment]
It turns out that adding it is covered in the readme file, so I can close this one.
