### ISSUE TITLE
Strange PathVariable naming @GetMapping("/files/{filename:.+}")

### ISSUE THREAD

**Issue by Illutax** [spring-guides/gs-uploading-files#73]
Not exactly an issue, with the code, but with the documentation of it. I've never seen this suffix of `:.+` in an PathVariable, nor have i found any documentation of the meaning.
What does it mean, and where can i learn more about it?

**Comment by wpn-zju** [comment]
[Read this](https://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated)
