### ISSUE TITLE
first upload is successful,but redirect to error uri

### ISSUE THREAD

**Issue by phxism** [spring-guides/gs-uploading-files#80]
(http://localhost:8080/;jsessionid=6FBBD3CDF59CE2D7C1A2DC6940584C8F) (Whitelabel Error Page)
`Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Apr 09 01:09:46 CST 2022
There was an unexpected error (type=Not Found, status=404).
You successfully uploaded avatar.jpg!`

**Comment by 43v3rn88b** [comment]
mine was fixed when I copy paste the exact code from the guide but when I try to upload >128kb it just shows this message:
This page isn’t working If the problem continues, contact the site owner.
HTTP ERROR 413

**Comment by phxism** [comment]
> mine was fixed when I copy paste the exact code from the guide but when I try to upload >128kb it just shows this message: This page isn’t working If the problem continues, contact the site owner. HTTP ERROR 413

because application.properties has a spring boot configuration for file upload **spring.servlet.multipart.max-request-size=128KB**
remove this line or change the 128KB bigger
